"""cendor-mcp — the Python (uvx) twin of the read-only Cendor docs MCP server.

Same five read-only tools, same answers as the TypeScript server (npx @cendor/mcp / the Cloudflare
Worker). Both read the SAME generated index (data/index.json, produced by scripts/build-index.mjs
from the sibling docs — never a copy of the docs themselves). The tool LOGIC here is a compact
mirror of ``src/tools.ts``; the ``mcp`` SDK provides the stdio transport.

The pure functions (``load_index``, ``run_tool``, ``TOOL_SPECS``) are stdlib-only and importable
without the ``mcp`` package, so they can be tested directly. Only ``serve`` imports ``mcp``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

_INDEX_PATH = Path(__file__).parent / "_data" / "index.json"


def load_index() -> dict[str, Any]:
    """Load the bundled docs index. Raises a clear error if the build step never ran."""
    if not _INDEX_PATH.exists():
        raise FileNotFoundError(
            f"docs index missing at {_INDEX_PATH}. It is generated by the Node build "
            "(`pnpm build:index` from the repo root, which also writes it here). See PUBLISHING.md."
        )
    return json.loads(_INDEX_PATH.read_text(encoding="utf-8"))


# ---------- shared helpers (mirror src/tools.ts) ----------


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def _norm_lang(x: Any) -> str | None:
    if not x:
        return None
    s = str(x).lower()
    if s.startswith("py"):
        return "python"
    if s.startswith(("ts", "type", "js", "java")):
        return "ts"
    return None


def _version_footer(index: dict[str, Any]) -> str:
    site = index["meta"]["site"]
    as_of = index["versions"].get("asOf", "")
    stamp = f" (as of {as_of})" if as_of else ""
    return (
        f"\n---\nCall-shapes are verified against the current published release{stamp}. "
        f"Exact per-package versions (PyPI `cendor-*` / npm `@cendor/*`): {site}/releases · "
        f"Full trap table & examples: {site}/docs/for-ai-assistants"
    )


# ---------- get_api ----------


def _score_trap(row: dict[str, Any], symbol: str) -> int:
    q = symbol.lower()
    qc = _norm(symbol)
    score = 0
    for sym in row["symbols"]:
        if sym == q:
            score = max(score, 100)
        elif _norm(sym) == qc:
            score = max(score, 90)
        elif q in sym or sym in q:
            score = max(score, 60)
        elif qc in _norm(sym) and len(qc) >= 3:
            score = max(score, 40)
    if score == 0:
        if qc in _norm(row["task"]) and len(qc) >= 3:
            score = 20
    return score


def _example_for(index: dict[str, Any], symbol: str) -> dict[str, Any] | None:
    qc = _norm(symbol)
    for ex in index["examples"]:
        if any(_norm(k) == qc or qc in _norm(k) for k in ex["keywords"]):
            return ex
    return None


def _render_trap(row: dict[str, Any], lang: str | None) -> str:
    out = [f"### {row['task']}"]
    if lang in (None, "python"):
        out.append(f"- **Python** — {row['python']}")
    if lang in (None, "ts"):
        out.append(f"- **TypeScript** — {row['typescript']}")
    out.append(f"- **Trap** — {row['trap']}")
    return "\n".join(out)


# ---------- example ----------


def _score_example(ex: dict[str, Any], task: str) -> int:
    terms = [t for t in re.split(r"[^a-z0-9]+", task.lower()) if len(t) > 1]
    hay = f"{ex['title']} {' '.join(ex['keywords'])}".lower()
    score = 0
    kws = {k.lower() for k in ex["keywords"]}
    for t in terms:
        if t in kws:
            score += 5
        elif t in hay:
            score += 2
    return score


def _render_example(ex: dict[str, Any], lang: str | None) -> str:
    out = [f"### {ex['title']}"]
    if lang in (None, "python") and ex["python"]:
        out.append(f"```python\n{ex['python']}\n```")
    if lang in (None, "ts") and ex["typescript"]:
        out.append(f"```ts\n{ex['typescript']}\n```")
    return "\n\n".join(out)


# ---------- get_page ----------


def _find_page(index: dict[str, Any], raw_slug: str) -> tuple[str, list[dict[str, Any]]]:
    slug = re.sub(r"^/?docs/", "", raw_slug.strip())
    slug = slug.lstrip("/").rstrip("/")
    product_hint: str | None = None
    m = re.match(r"^(libraries|libs|sdk|parity)[:/](.+)$", slug)
    if m:
        product_hint = "libraries" if m.group(1) == "libs" else m.group(1)
        slug = m.group(2)
    if slug in ("", "docs"):
        slug = "index"
    matches = [
        p
        for p in index["pages"]
        if p["slug"] == slug and (not product_hint or p["product"] == product_hint)
    ]
    return slug, matches


# ---------- search ----------


def _tokenize(s: str) -> list[str]:
    return [t for t in re.findall(r"[a-z0-9_.]+", s.lower()) if len(t) > 1]


def _search_docs(index: dict[str, Any], query: str, limit: int = 6) -> list[dict[str, Any]]:
    terms = _tokenize(query)
    if not terms:
        return []
    hits = []
    for chunk in index["chunks"]:
        hay_title = f"{chunk['title']} {chunk['heading']}".lower()
        hay_text = chunk["text"].lower()
        score = 0
        for t in terms:
            if t in hay_title:
                score += 6
            score += min(hay_text.count(t), 5)
        if score > 0:
            flat = re.sub(r"\s+", " ", chunk["text"]).strip()
            hits.append(
                {
                    "title": chunk["title"],
                    "url": chunk["url"],
                    "product": chunk["product"],
                    "snippet": (flat[:240] + "…") if len(flat) > 240 else flat,
                    "score": score,
                }
            )
    hits.sort(key=lambda h: h["score"], reverse=True)
    return hits[:limit]


# ---------- tool registry + dispatch ----------

TOOL_SPECS: list[dict[str, Any]] = [
    {
        "name": "search_docs",
        "title": "Search Cendor docs",
        "description": (
            "Full-text search over the Cendor documentation (the seven libraries, the SDK, and the "
            "TypeScript parity matrix). Returns top matching sections with titles + canonical "
            "https://cendor.ai URLs. Use this to discover which library/API to reach for."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Natural-language or keyword query."},
                "limit": {"type": "number", "description": "Max results (default 6, max 15)."},
            },
            "required": ["query"],
            "additionalProperties": False,
        },
    },
    {
        "name": "get_page",
        "title": "Get a Cendor docs page",
        "description": (
            'Return a full Cendor docs page as markdown, given its slug (e.g. "tokenguard", '
            '"getting-started", or an SDK page as "sdk/agents"). Slugs in both products default to '
            'the libraries page; prefix "sdk/" for the SDK version.'
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "slug": {
                    "type": "string",
                    "description": 'Page slug, e.g. "core", "for-ai-assistants", "sdk/agents".',
                }
            },
            "required": ["slug"],
            "additionalProperties": False,
        },
    },
    {
        "name": "get_api",
        "title": "Get the correct Cendor call-shape",
        "description": (
            "The anti-hallucination tool. Given a Cendor symbol (e.g. \"budget\", "
            '"prices.estimate", "instrument", "SqliteSessionStore") return its CURRENT correct '
            "call-shape and the common wrong shape to avoid, from the maintained trap registry. "
            'Optionally scope to a language ("python" or "ts"); omit for both.'
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "symbol": {
                    "type": "string",
                    "description": 'A Cendor API symbol, e.g. "budget", "prices.estimate".',
                },
                "lang": {
                    "type": "string",
                    "enum": ["python", "ts"],
                    "description": "Optional language filter. Omit to show both.",
                },
            },
            "required": ["symbol"],
            "additionalProperties": False,
        },
    },
    {
        "name": "example",
        "title": "Get a runnable Cendor snippet",
        "description": (
            'Return a runnable, CI-typechecked Cendor snippet for a task ("budget a loop", "gate '
            'input", "assemble context", "record a test", "count tokens", "instrument a client"). '
            'Optionally scope to a language ("python" or "ts"); omit for both.'
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "task": {"type": "string", "description": "What you want to do, in plain words."},
                "lang": {
                    "type": "string",
                    "enum": ["python", "ts"],
                    "description": "Optional language filter. Omit to show both.",
                },
            },
            "required": ["task"],
            "additionalProperties": False,
        },
    },
    {
        "name": "list_recipes",
        "title": "List Cendor cookbook recipes",
        "description": (
            "Link out to the Cendor cookbook — copy-paste recipes that run offline (cassette, no "
            "API key). Recipes live in the cendor-cookbook repo; returns the index + categories."
        ),
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
]


def _t_search_docs(index: dict[str, Any], args: dict[str, Any]) -> str:
    query = str(args.get("query", "")).strip()
    if not query:
        return "Provide a non-empty `query`."
    limit = max(1, min(15, int(args.get("limit") or 6)))
    hits = _search_docs(index, query, limit)
    if not hits:
        return f'No matches for "{query}". Try a library name: tokenguard, guardrails, cassette.'
    body = "\n".join(
        f"- **{h['title']}** _({h['product']})_\n  {h['url']}\n  {h['snippet']}" for h in hits
    )
    return f'Top {len(hits)} matches for "{query}":\n\n{body}{_version_footer(index)}'


def _t_get_page(index: dict[str, Any], args: dict[str, Any]) -> str:
    raw = str(args.get("slug", "")).strip()
    if not raw:
        return 'Provide a `slug` (try `search_docs` first, or "index" for the docs home).'
    slug, matches = _find_page(index, raw)
    if not matches:
        known = ", ".join(
            (f"sdk/{p['slug']}" if p["product"] == "sdk" else p["slug"]) for p in index["pages"]
        )
        return f'No page "{slug}". Known slugs: {known}.'
    page = next((p for p in matches if p["product"] == "libraries"), matches[0])
    others = [f"{p['product']}/{p['slug']}" for p in matches if p is not page]
    alt = f"\n\n> Also available: {', '.join(others)}" if others else ""
    src = f"Source: {page['url']}\n\n" if page["url"] else ""
    return f"# {page['title']}\n{src}{page['body']}{alt}"


def _t_get_api(index: dict[str, Any], args: dict[str, Any]) -> str:
    symbol = str(args.get("symbol", "")).strip()
    if not symbol:
        return 'Provide a `symbol`, e.g. "budget" or "prices.estimate".'
    lang = _norm_lang(args.get("lang"))
    ranked = sorted(
        ((r, _score_trap(r, symbol)) for r in index["traps"]),
        key=lambda x: x[1],
        reverse=True,
    )
    ranked = [(r, s) for r, s in ranked if s > 0]
    if not ranked:
        tasks = "; ".join(t["task"] for t in index["traps"])
        return f'No trap-table entry matches "{symbol}". Try search_docs, or a task: {tasks}.'
    top_row, top_score = ranked[0]
    parts = [_render_trap(top_row, lang)]
    if top_score >= 60:
        ex = _example_for(index, symbol)
        if ex:
            parts.append(f"\n**Canonical example — {ex['title']}:**\n\n{_render_example(ex, lang)}")
    more = [r["task"] for r, s in ranked[1:4] if s >= 40]
    if more:
        parts.append(f"\n_Related:_ {'; '.join(more)}.")
    return "\n".join(parts) + _version_footer(index)


def _t_example(index: dict[str, Any], args: dict[str, Any]) -> str:
    task = str(args.get("task", "")).strip()
    if not task:
        return 'Provide a `task`, e.g. "budget a loop" or "gate unsafe input".'
    lang = _norm_lang(args.get("lang"))
    ranked = sorted(
        ((ex, _score_example(ex, task)) for ex in index["examples"]),
        key=lambda x: x[1],
        reverse=True,
    )
    ranked = [(ex, s) for ex, s in ranked if s > 0]
    if not ranked:
        titles = "; ".join(e["title"] for e in index["examples"])
        return f'No canonical example matches "{task}". Available: {titles}.'
    best = ranked[0][0]
    others = [ex["title"] for ex, _ in ranked[1:4]]
    alt = f"\n\n_Other examples:_ {'; '.join(others)}." if others else ""
    return _render_example(best, lang) + alt + _version_footer(index)


def _t_list_recipes(index: dict[str, Any], _args: dict[str, Any]) -> str:
    r = index["recipes"]
    cats = f"\n\nCategories: {', '.join(r['categories'])}." if r["categories"] else ""
    return (
        "Cendor cookbook — copy-paste recipes, offline (cassette-recorded, no API key):\n"
        f"- Browse: {r['url']}\n- Source: {r['github']}{cats}"
    )


_HANDLERS = {
    "search_docs": _t_search_docs,
    "get_page": _t_get_page,
    "get_api": _t_get_api,
    "example": _t_example,
    "list_recipes": _t_list_recipes,
}


def run_tool(index: dict[str, Any], name: str, args: dict[str, Any]) -> str:
    handler = _HANDLERS.get(name)
    if handler is None:
        return f"Unknown tool: {name}"
    return handler(index, args)


# ---------- mcp stdio server (imports the mcp SDK lazily) ----------


async def serve() -> None:
    import mcp.types as types
    from mcp.server import Server
    from mcp.server.stdio import stdio_server

    index = load_index()
    server: Server = Server("cendor-mcp")

    @server.list_tools()
    async def _list_tools() -> list[types.Tool]:  # pyright: ignore[reportUnusedFunction]
        return [
            types.Tool(
                name=t["name"],
                title=t["title"],
                description=t["description"],
                inputSchema=t["inputSchema"],
            )
            for t in TOOL_SPECS
        ]

    @server.call_tool()
    async def _call_tool(  # pyright: ignore[reportUnusedFunction]
        name: str, arguments: dict[str, Any]
    ) -> list[types.TextContent]:
        return [types.TextContent(type="text", text=run_tool(index, name, arguments or {}))]

    async with stdio_server() as (read, write):
        await server.run(read, write, server.create_initialization_options())
